package com.saama.workbench.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditJobs generated by hbm2java
 */
@Entity
@Table(name="AUDIT_JOBS"
    ,schema="AUX"
   
)
@SequenceGenerator(name = "AuditJobs_SEQ", sequenceName = "AuditJobs_SEQ")
public class AuditJobs  implements java.io.Serializable {


    
     private String layer;
     private String source;
     private String fileName;
     private String processName;
     private String jobName;
     private String transformationName;
     private Date startTime;
     private Date endTime;
     private Integer recordsRead;
     private Integer recordsWritten;
     private Integer rejects;
     private String status;
     private String failureReason;
     private Integer batchId;
     private Date createdDate;
     private String createdBy;
     private Date updatedDate;
     private String updatedBy;
     private long auditJobId;
     private String subjectArea;
     

    public AuditJobs() {
    }

	
 
    public AuditJobs( String layer, String source, String fileName, String processName, String jobName, String transformationName, Date startTime, Date endTime, Integer recordsRead, Integer recordsWritten, Integer rejects, String status, String failureReason, Integer batchId, Date createdDate, String createdBy, Date updatedDate, String updatedBy, long auditJobId,String subjectArea) {
       
       this.layer = layer;
       this.source = source;
       this.fileName = fileName;
       this.processName = processName;
       this.jobName = jobName;
       this.transformationName = transformationName;
       this.startTime = startTime;
       this.endTime = endTime;
       this.recordsRead = recordsRead;
       this.recordsWritten = recordsWritten;
       this.rejects = rejects;
       this.status = status;
       this.failureReason = failureReason;
       this.batchId = batchId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.updatedDate = updatedDate;
       this.updatedBy = updatedBy;
       this.auditJobId = auditJobId;
       this.subjectArea = subjectArea;
    }
   
    
   

    
    @Column(name="Layer", length=64)
    public String getLayer() {
        return this.layer;
    }
    
    public void setLayer(String layer) {
        this.layer = layer;
    }

    
    @Column(name="Source", length=64)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="FileName", length=64)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="ProcessName", length=64)
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }

    
    @Column(name="JobName", length=64)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="TransformationName", length=64)
    public String getTransformationName() {
        return this.transformationName;
    }
    
    public void setTransformationName(String transformationName) {
        this.transformationName = transformationName;
    }

    
    @Column(name="StartTime", length=23)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date string) {
        this.startTime = string;
    }

    
    @Column(name="EndTime", length=23)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="RecordsRead")
    public Integer getRecordsRead() {
        return this.recordsRead;
    }
    
    public void setRecordsRead(Integer recordsRead) {
        this.recordsRead = recordsRead;
    }

    
    @Column(name="RecordsWritten")
    public Integer getRecordsWritten() {
        return this.recordsWritten;
    }
    
    public void setRecordsWritten(Integer recordsWritten) {
        this.recordsWritten = recordsWritten;
    }

    
    @Column(name="Rejects")
    public Integer getRejects() {
        return this.rejects;
    }
    
    public void setRejects(Integer rejects) {
        this.rejects = rejects;
    }

    
    @Column(name="Status", length=64)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="FailureReason", length=512)
    public String getFailureReason() {
        return this.failureReason;
    }
    
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    
    @Column(name="BatchID")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=64)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="UpdatedBy", length=64)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    
    @Id 

    @GeneratedValue(generator = "AuditJobs_SEQ", strategy = GenerationType.IDENTITY)
    @Column(name="AuditJobID", unique=true, nullable=false)
    public long getAuditJobId() {
        return this.auditJobId;
    }
    
    public void setAuditJobId(long auditJobId) {
        this.auditJobId = auditJobId;
    }

    @Column(name="SubjectArea", nullable=false)
	public String getSubjectArea() {
		return subjectArea;
	}


	public void setSubjectArea(String subjectArea) {
		this.subjectArea = subjectArea;
	}




}


