package com.saama.workbench.model;

//Generated 20 May, 2016 12:26:57 PM by Hibernate Tools 3.6.0



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerStats generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_STATS"
    ,schema="AUX"
    
)
public class CustomerStats  implements java.io.Serializable {


    private long customerStatsId;
    private String account;
    private String promotionEndMonth;
    private String promotionEndYear;
    private Long shipmentVolume;
    private Long eposvolume;
    private Double sellOutToshipmentRatio;
    private Double currentToprevMonthRatio;
    private Date createdDate;
    private String createdBy;
    private Date updatedDate;
    private String updatedBy;

   public CustomerStats() {
   }

	
   public CustomerStats(long customerStatsId) {
       this.customerStatsId = customerStatsId;
   }
   public CustomerStats(long customerStatsId, String account, String promotionEndMonth, String promotionEndYear, Long shipmentVolume, Long eposvolume, Double sellOutToshipmentRatio, Double currentToprevMonthRatio, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
      this.customerStatsId = customerStatsId;
      this.account = account;
      this.promotionEndMonth = promotionEndMonth;
      this.promotionEndYear = promotionEndYear;
      this.shipmentVolume = shipmentVolume;
      this.eposvolume = eposvolume;
      this.sellOutToshipmentRatio = sellOutToshipmentRatio;
      this.currentToprevMonthRatio = currentToprevMonthRatio;
      this.createdDate = createdDate;
      this.createdBy = createdBy;
      this.updatedDate = updatedDate;
      this.updatedBy = updatedBy;
   }
  
    @Id 

   
   @Column(name="CustomerStatsID", unique=true, nullable=false)
   public long getCustomerStatsId() {
       return this.customerStatsId;
   }
   
   public void setCustomerStatsId(long customerStatsId) {
       this.customerStatsId = customerStatsId;
   }

   
   @Column(name="Account", length=128)
   public String getAccount() {
       return this.account;
   }
   
   public void setAccount(String account) {
       this.account = account;
   }

   
   @Column(name="PromotionEndMonth", length=64)
   public String getPromotionEndMonth() {
       return this.promotionEndMonth;
   }
   
   public void setPromotionEndMonth(String promotionEndMonth) {
       this.promotionEndMonth = promotionEndMonth;
   }

   
   @Column(name="PromotionEndYear", length=64)
   public String getPromotionEndYear() {
       return this.promotionEndYear;
   }
   
   public void setPromotionEndYear(String promotionEndYear) {
       this.promotionEndYear = promotionEndYear;
   }

   
   @Column(name="ShipmentVolume", precision=20, scale=4)
   public Long getShipmentVolume() {
       return this.shipmentVolume;
   }
   
   public void setShipmentVolume(Long shipmentVolume) {
       this.shipmentVolume = shipmentVolume;
   }

   
   @Column(name="EPOSVolume", precision=20, scale=4)
   public Long getEposvolume() {
       return this.eposvolume;
   }
   
   public void setEposvolume(Long eposvolume) {
       this.eposvolume = eposvolume;
   }

   
   @Column(name="SellOutTOShipmentRatio", precision=10)
   public Double getSellOutToshipmentRatio() {
       return this.sellOutToshipmentRatio;
   }
   
   public void setSellOutToshipmentRatio(Double sellOutToshipmentRatio) {
       this.sellOutToshipmentRatio = sellOutToshipmentRatio;
   }

   
   @Column(name="CurrentTOPrevMonthRatio", precision=10)
   public Double getCurrentToprevMonthRatio() {
       return this.currentToprevMonthRatio;
   }
   
   public void setCurrentToprevMonthRatio(Double currentToprevMonthRatio) {
       this.currentToprevMonthRatio = currentToprevMonthRatio;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="CreatedDate", length=23)
   public Date getCreatedDate() {
       return this.createdDate;
   }
   
   public void setCreatedDate(Date createdDate) {
       this.createdDate = createdDate;
   }

   
   @Column(name="CreatedBy", length=3)
   public String getCreatedBy() {
       return this.createdBy;
   }
   
   public void setCreatedBy(String createdBy) {
       this.createdBy = createdBy;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="UpdatedDate", length=23)
   public Date getUpdatedDate() {
       return this.updatedDate;
   }
   
   public void setUpdatedDate(Date updatedDate) {
       this.updatedDate = updatedDate;
   }

   
   @Column(name="UpdatedBy", length=3)
   public String getUpdatedBy() {
       return this.updatedBy;
   }
   
   public void setUpdatedBy(String updatedBy) {
       this.updatedBy = updatedBy;
   }




}


