package com.saama.workbench.model;
// Generated 17 May, 2016 11:18:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerHierarchyBase generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_HIERARCHY_BASE"
    ,schema="CNF"
    
)
public class CustomerHierarchyBase  implements java.io.Serializable {


     private long custHierarchyBaseId;
     private String customerName;
     private String loc;
     private String customerStatus;
     private String apgidentifier;
     private String planningAccountFlag;
     private String naturalKeyHash;
     private String rowHash;
     private Integer batchId;
     private Date createdDate;
     private String createdBy;
     private Date updatedDate;
     private String updatedBy;

    public CustomerHierarchyBase() {
    }

	
    public CustomerHierarchyBase(long custHierarchyBaseId) {
        this.custHierarchyBaseId = custHierarchyBaseId;
    }
    public CustomerHierarchyBase(long custHierarchyBaseId, String customerName, String loc, String customerStatus, String apgidentifier, String planningAccountFlag, String countryCode, String naturalKeyHash, String rowHash, Integer batchId, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
       this.custHierarchyBaseId = custHierarchyBaseId;
       this.customerName = customerName;
       this.loc = loc;
       this.customerStatus = customerStatus;
       this.apgidentifier = apgidentifier;
       this.planningAccountFlag = planningAccountFlag;
       this.naturalKeyHash = naturalKeyHash;
       this.rowHash = rowHash;
       this.batchId = batchId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.updatedDate = updatedDate;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="CustHierarchyBaseID", unique=true, nullable=false)
    public long getCustHierarchyBaseId() {
        return this.custHierarchyBaseId;
    }
    
    public void setCustHierarchyBaseId(long custHierarchyBaseId) {
        this.custHierarchyBaseId = custHierarchyBaseId;
    }

    
    @Column(name="CustomerName", length=64)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="LOC", length=16)
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }

    
    @Column(name="CustomerStatus", length=64)
    public String getCustomerStatus() {
        return this.customerStatus;
    }
    
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus;
    }

    
    @Column(name="APGIdentifier", length=16)
    public String getApgidentifier() {
        return this.apgidentifier;
    }
    
    public void setApgidentifier(String apgidentifier) {
        this.apgidentifier = apgidentifier;
    }

    
    @Column(name="PlanningAccountFlag", length=1)
    public String getPlanningAccountFlag() {
        return this.planningAccountFlag;
    }
    
    public void setPlanningAccountFlag(String planningAccountFlag) {
        this.planningAccountFlag = planningAccountFlag;
    }

    
    @Column(name="NaturalKeyHash", length=32)
    public String getNaturalKeyHash() {
        return this.naturalKeyHash;
    }
    
    public void setNaturalKeyHash(String naturalKeyHash) {
        this.naturalKeyHash = naturalKeyHash;
    }

    
    @Column(name="RowHash", length=32)
    public String getRowHash() {
        return this.rowHash;
    }
    
    public void setRowHash(String rowHash) {
        this.rowHash = rowHash;
    }

    
    @Column(name="BatchID")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=64)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="UpdatedBy", length=64)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


