package com.saama.workbench.model;
// Generated 17 May, 2016 11:18:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerHierarchyLevel generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_HIERARCHY_LEVEL"
    ,schema="CNF"
    
)
public class CustomerHierarchyLevel  implements java.io.Serializable {


     private long custHierarchyLevelId;
     private long custHierarchyBaseId;
     private String name;
     private String code;
     private String level;
     private String description;
     private String naturalKeyHash;
     private String rowHash;
     private Integer batchId;
     private Date createdDate;
     private String createdBy;
     private Date updatedDate;
     private String updatedBy;

    public CustomerHierarchyLevel() {
    }

	
    public CustomerHierarchyLevel(long custHierarchyLevelId, long custHierarchyBaseId) {
        this.custHierarchyLevelId = custHierarchyLevelId;
        this.custHierarchyBaseId = custHierarchyBaseId;
    }
    public CustomerHierarchyLevel(long custHierarchyLevelId, long custHierarchyBaseId, String name, String code, String level, String description, String naturalKeyHash, String rowHash, Integer batchId, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
       this.custHierarchyLevelId = custHierarchyLevelId;
       this.custHierarchyBaseId = custHierarchyBaseId;
       this.name = name;
       this.code = code;
       this.level = level;
       this.description = description;
       this.naturalKeyHash = naturalKeyHash;
       this.rowHash = rowHash;
       this.batchId = batchId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.updatedDate = updatedDate;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="CustHierarchyLevelID", unique=true, nullable=false)
    public long getCustHierarchyLevelId() {
        return this.custHierarchyLevelId;
    }
    
    public void setCustHierarchyLevelId(long custHierarchyLevelId) {
        this.custHierarchyLevelId = custHierarchyLevelId;
    }

    
    @Column(name="CustHierarchyBaseID", nullable=false)
    public long getCustHierarchyBaseId() {
        return this.custHierarchyBaseId;
    }
    
    public void setCustHierarchyBaseId(long custHierarchyBaseId) {
        this.custHierarchyBaseId = custHierarchyBaseId;
    }

    
    @Column(name="Name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Code", length=32)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="Level", length=2)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    
    @Column(name="Description", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NaturalKeyHash", length=32)
    public String getNaturalKeyHash() {
        return this.naturalKeyHash;
    }
    
    public void setNaturalKeyHash(String naturalKeyHash) {
        this.naturalKeyHash = naturalKeyHash;
    }

    
    @Column(name="RowHash", length=32)
    public String getRowHash() {
        return this.rowHash;
    }
    
    public void setRowHash(String rowHash) {
        this.rowHash = rowHash;
    }

    
    @Column(name="BatchID")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=64)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="UpdatedBy", length=64)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


