package com.saama.workbench.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * DatasetMeta generated by hbm2java
 */
@Entity
@Table(name="DATASET_DIM"
    ,schema="PRS"    
)
@SequenceGenerator(name = "DatasetMeta_SEQ", sequenceName = "DatasetMeta_SEQ")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "datasetMeta")
public class DatasetMeta  implements java.io.Serializable {


     private long datasetId;
     private String datasetName;
     private String datasetType;
     private  String productMappingId;
     private  String customerMappingId;
     private Byte dateFilter;
     private Date startingDate;
     private String pentahoBatchId;
     private Date endingDate;
     private String notes;
     private String runType;
     private String processStatus;
     private String countryCode;
     private Long countryId;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     
     private String isActive;

    public DatasetMeta() {
    }

	
    public DatasetMeta(long datasetId) {
        this.datasetId = datasetId;
    }
    public DatasetMeta(long datasetId, String datasetName, String datasetType, String productMappingId, String customerMappingId, Byte dateFilter, String startingDate, String pentahoBatchId, String endingDate, String notes, String runType, String processStatus, String countryCode, Long countryId, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
       this.datasetId = datasetId;
       this.datasetName = datasetName;
       this.datasetType = datasetType;
       this.productMappingId = productMappingId;
       this.customerMappingId = customerMappingId;
       this.dateFilter = dateFilter;
       this.pentahoBatchId = pentahoBatchId;
       this.notes = notes;
       this.runType = runType;
       this.processStatus = processStatus;
       this.countryCode = countryCode;
       this.countryId = countryId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
     @Id 

    @GeneratedValue(generator = "DatasetMeta_SEQ", strategy = GenerationType.AUTO)
    @Column(name="DatasetID", unique=true, nullable=false)
    public long getDatasetId() {
        return this.datasetId;
    }
    
    public void setDatasetId(long datasetId) {
        this.datasetId = datasetId;
    }

    
    @Column(name="DatasetName")
    public String getDatasetName() {
        return this.datasetName;
    }
    
    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    
    @Column(name="DatasetType")
    public String getDatasetType() {
        return this.datasetType;
    }
    
    public void setDatasetType(String datasetType) {
        this.datasetType = datasetType;
    }

    
    @Column(name="ProductMappingID",columnDefinition = "varchar(max)")
    public String getProductMappingId() {
        return this.productMappingId;
    }
    
    public void setProductMappingId(String productMappingId) {
        this.productMappingId = productMappingId;
    }

    
    @Column(name="CustomerMappingID",columnDefinition = "varchar(max)")
    public String getCustomerMappingId() {
        return this.customerMappingId;
    }
    
    public void setCustomerMappingId(String customerMappingId) {
        this.customerMappingId = customerMappingId;
    }

    
    @Column(name="DateFilter")
    public Byte getDateFilter() {
        return this.dateFilter;
    }
    
    public void setDateFilter(Byte dateFilter) {
        this.dateFilter = dateFilter;
    }

    
    @Column(name="StartingDate", length=10)
    public Date getStartingDate() {
        return this.startingDate;
    }
    
    public void setStartingDate(Date startingDate) {
        this.startingDate = startingDate;
    }

    
    @Column(name="PentahoBatchID", length=128)
    public String getPentahoBatchId() {
        return this.pentahoBatchId;
    }
    
    public void setPentahoBatchId(String pentahoBatchId) {
        this.pentahoBatchId = pentahoBatchId;
    }

    
    @Column(name="EndingDate", length=10)
    public Date getEndingDate() {
        return this.endingDate;
    }
    
    public void setEndingDate(Date endingDate) {
        this.endingDate = endingDate;
    }

    
    @Column(name="Notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="RunType")
    public String getRunType() {
        return this.runType;
    }
    
    public void setRunType(String runType) {
        this.runType = runType;
    }

    
    @Column(name="ProcessStatus")
    public String getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    
    @Column(name="CountryCode", length=12)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="CountryID")
    public Long getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="CreatedBy", length=64)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="UpdatedBy", length=64)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="isActive", length=1)
	public String getIsActive() {
		return isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}




}


