package com.saama.workbench.model;
// Generated 17 May, 2016 11:18:19 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductHierarchyBase generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_HIERARCHY_BASE"
    ,schema="CNF"
    
)
public class ProductHierarchyBase  implements java.io.Serializable {


     private long prodHierarchyBaseId;
     private String productName;
     private String activeForSalesFlag;
     private String activeFlag;
     private String mrdrcode;
     private String partNumber;
     private String tuean;
     private String cuean;
     private String idocNumber;
     private BigDecimal productCost;
     private String naturalKeyHash;
     private String rowHash;
     private Integer batchId;
     private Date createdDate;
     private String createdBy;
     private Date updatedDate;
     private String updatedBy;

    public ProductHierarchyBase() {
    }

	
    public ProductHierarchyBase(long prodHierarchyBaseId) {
        this.prodHierarchyBaseId = prodHierarchyBaseId;
    }
    public ProductHierarchyBase(long prodHierarchyBaseId, String productName, String activeForSalesFlag, String activeFlag, String mrdrcode, String partNumber, String tuean, String cuean, String idocNumber, String srcDateLastSent, BigDecimal productCost, String srcLastUpdate, String naturalKeyHash, String rowHash, Integer batchId, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
       this.prodHierarchyBaseId = prodHierarchyBaseId;
       this.productName = productName;
       this.activeForSalesFlag = activeForSalesFlag;
       this.activeFlag = activeFlag;
       this.mrdrcode = mrdrcode;
       this.partNumber = partNumber;
       this.tuean = tuean;
       this.cuean = cuean;
       this.idocNumber = idocNumber;
       this.productCost = productCost;
       this.naturalKeyHash = naturalKeyHash;
       this.rowHash = rowHash;
       this.batchId = batchId;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.updatedDate = updatedDate;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="ProdHierarchyBaseID", unique=true, nullable=false)
    public long getProdHierarchyBaseId() {
        return this.prodHierarchyBaseId;
    }
    
    public void setProdHierarchyBaseId(long prodHierarchyBaseId) {
        this.prodHierarchyBaseId = prodHierarchyBaseId;
    }

    
    @Column(name="ProductName", length=64)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="ActiveForSalesFlag", length=1)
    public String getActiveForSalesFlag() {
        return this.activeForSalesFlag;
    }
    
    public void setActiveForSalesFlag(String activeForSalesFlag) {
        this.activeForSalesFlag = activeForSalesFlag;
    }

    
    @Column(name="ActiveFlag", length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="MRDRCode", length=16)
    public String getMrdrcode() {
        return this.mrdrcode;
    }
    
    public void setMrdrcode(String mrdrcode) {
        this.mrdrcode = mrdrcode;
    }

    
    @Column(name="PartNumber", length=32)
    public String getPartNumber() {
        return this.partNumber;
    }
    
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber;
    }

    
    @Column(name="TUEAN", length=32)
    public String getTuean() {
        return this.tuean;
    }
    
    public void setTuean(String tuean) {
        this.tuean = tuean;
    }

    
    @Column(name="CUEAN", length=32)
    public String getCuean() {
        return this.cuean;
    }
    
    public void setCuean(String cuean) {
        this.cuean = cuean;
    }

    
    @Column(name="IdocNumber", length=32)
    public String getIdocNumber() {
        return this.idocNumber;
    }
    
    public void setIdocNumber(String idocNumber) {
        this.idocNumber = idocNumber;
    }

    
    @Column(name="ProductCost", precision=20, scale=4)
    public BigDecimal getProductCost() {
        return this.productCost;
    }
    
    public void setProductCost(BigDecimal productCost) {
        this.productCost = productCost;
    }

    
    @Column(name="NaturalKeyHash", length=32)
    public String getNaturalKeyHash() {
        return this.naturalKeyHash;
    }
    
    public void setNaturalKeyHash(String naturalKeyHash) {
        this.naturalKeyHash = naturalKeyHash;
    }

    
    @Column(name="RowHash", length=32)
    public String getRowHash() {
        return this.rowHash;
    }
    
    public void setRowHash(String rowHash) {
        this.rowHash = rowHash;
    }

    
    @Column(name="BatchID")
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreatedDate", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="CreatedBy", length=64)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UpdatedDate", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="UpdatedBy", length=64)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


