package com.saama.workbench.model;


//Generated 7 Jun, 2016 12:23:29 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* PromotionFact generated by hbm2java
*/
@Entity
@Table(name="PROMOTION_FACT"
 ,schema="PRS"
 
)
public class PromotionFact  implements java.io.Serializable {


  private long promotionFactId;
  private Long promotionId;
  private Long productId;
  private Long customerId;
  private BigDecimal baseShipmentUnits;
  private BigDecimal baseShipmentCases;
  private BigDecimal baseUnitVolume;
  private BigDecimal plannedBaselineDeviationPerc;
  private BigDecimal totalShippedUnits;
  private BigDecimal totalShippedCases;
  private BigDecimal totalScannedUnits;
  private BigDecimal totalUnitVolume;
  private BigDecimal incrementalUnitVolume;
  private BigDecimal plannedTotalShippedUnits;
  private BigDecimal plannedTotalShippedCases;
  private BigDecimal plannedSellOutUnitVolume;
  private BigDecimal plannedIncrementalUnitVolume;
  private BigDecimal plannedIncrementalShippedUnits;
  private BigDecimal plannedIncrementalShippedCases;
  private BigDecimal plannedDipUnits;
  private BigDecimal adjustmentUnits;
  private BigDecimal cannibalisedUnits;
  private BigDecimal cannibalisedCases;
  private BigDecimal cannibalisedGsv;
  private BigDecimal cannibalisedTurnover;
  private BigDecimal cannibalisedGrossProfit;
  private BigDecimal unitsperCase;
  private BigDecimal plannedFixedTradeSpend;
  private BigDecimal tradeRateperCaseOnInvoice;
  private BigDecimal tradeRateperCaseOffInvoice;
  private BigDecimal tradeRatePercentofNivonInvoice;
  private BigDecimal tradeRatePercentofNivoffInvoice;
  private BigDecimal plannedGsvperUnit;
  private BigDecimal plannedNsvperUnit;
  private BigDecimal plannedCogsperUnit;
  private BigDecimal plannedTurnoverperUnit;
  private BigDecimal plannedGrossProfitperUnit;
  private BigDecimal baseGsv;
  private BigDecimal baseNsv;
  private BigDecimal baseCogs;
  private BigDecimal baseGrossProfit;
  private BigDecimal baseGrossMargin;
  private BigDecimal plannedTotalGsv;
  private BigDecimal plannedTotalGsvsellIn;
  private BigDecimal plannedTotalNsv;
  private BigDecimal plannedTotalNsvsellIn;
  private BigDecimal plannedTradeSpend;
  private BigDecimal plannedTotalTurnover;
  private BigDecimal plannedTotalTurnoverSellIn;
  private BigDecimal plannedTotalCogs;
  private BigDecimal plannedTotalCogssellIn;
  private BigDecimal plannedTotalGrossProfit;
  private BigDecimal plannedIncrementalGsv;
  private BigDecimal plannedIncrementalNsv;
  private BigDecimal plannedIncrementalTurnover;
  private BigDecimal plannedIncrementalGrossProfit;
  private BigDecimal plannedRoi;
  private BigDecimal plannedGrossMargin;
  private BigDecimal plannedVolumeUplift;
  private BigDecimal plannedBreakevenUnitVolume;
  private BigDecimal plannedBreakevenUplift;
  private BigDecimal opsoweightingFactor;
  private BigDecimal opsototalGsv;
  private BigDecimal opsototalNsv;
  private BigDecimal opsotradeSpend;
  private BigDecimal opsototalTurnover;
  private BigDecimal opsototalGrossProfit;
  private BigDecimal opsoincrementalGsv;
  private BigDecimal opsoincrementalNsv;
  private BigDecimal opsoincrementalTurnover;
  private BigDecimal opsoincrementalGrossProfit;
  private BigDecimal opsoroi;
  private BigDecimal opsogrossMargin;
  private BigDecimal actualTotalGsv;
  private BigDecimal actualTotalGsvsellIn;
  private BigDecimal actualTotalNsv;
  private BigDecimal actualTradeSpend;
  private BigDecimal actualTotalTurnover;
  private BigDecimal actualTotalCogs;
  private BigDecimal actualTotalGrossProfit;
  private BigDecimal actualIncrementalGsv;
  private BigDecimal actualIncrementalNsv;
  private BigDecimal actualIncrementalTurnover;
  private BigDecimal actualIncrementalGrossProfit;
  private BigDecimal actualRoi;
  private BigDecimal actualGrossMargin;
  private BigDecimal volumeUplift;
  private String exceptionFlag;
  private Long businessRuleId;
  private Integer batchId;
  private Date createdDate;
  private String createdBy;

 public PromotionFact() {
 }

	
 public PromotionFact(long promotionFactId) {
     this.promotionFactId = promotionFactId;
 }
 public PromotionFact(long promotionFactId, Long promotionId, Long productId, Long customerId, BigDecimal baseShipmentUnits, BigDecimal baseShipmentCases, BigDecimal baseUnitVolume, BigDecimal plannedBaselineDeviationPerc, BigDecimal totalShippedUnits, BigDecimal totalShippedCases, BigDecimal totalScannedUnits, BigDecimal totalUnitVolume, BigDecimal incrementalUnitVolume, BigDecimal plannedTotalShippedUnits, BigDecimal plannedTotalShippedCases, BigDecimal plannedSellOutUnitVolume, BigDecimal plannedIncrementalUnitVolume, BigDecimal plannedIncrementalShippedUnits, BigDecimal plannedIncrementalShippedCases, BigDecimal plannedDipUnits, BigDecimal adjustmentUnits, BigDecimal cannibalisedUnits, BigDecimal cannibalisedCases, BigDecimal cannibalisedGsv, BigDecimal cannibalisedTurnover, BigDecimal cannibalisedGrossProfit, BigDecimal unitsperCase, BigDecimal plannedFixedTradeSpend, BigDecimal tradeRateperCaseOnInvoice, BigDecimal tradeRateperCaseOffInvoice, BigDecimal tradeRatePercentofNivonInvoice, BigDecimal tradeRatePercentofNivoffInvoice, BigDecimal plannedGsvperUnit, BigDecimal plannedNsvperUnit, BigDecimal plannedCogsperUnit, BigDecimal plannedTurnoverperUnit, BigDecimal plannedGrossProfitperUnit, BigDecimal baseGsv, BigDecimal baseNsv, BigDecimal baseCogs, BigDecimal baseGrossProfit, BigDecimal baseGrossMargin, BigDecimal plannedTotalGsv, BigDecimal plannedTotalGsvsellIn, BigDecimal plannedTotalNsv, BigDecimal plannedTotalNsvsellIn, BigDecimal plannedTradeSpend, BigDecimal plannedTotalTurnover, BigDecimal plannedTotalTurnoverSellIn, BigDecimal plannedTotalCogs, BigDecimal plannedTotalCogssellIn, BigDecimal plannedTotalGrossProfit, BigDecimal plannedIncrementalGsv, BigDecimal plannedIncrementalNsv, BigDecimal plannedIncrementalTurnover, BigDecimal plannedIncrementalGrossProfit, BigDecimal plannedRoi, BigDecimal plannedGrossMargin, BigDecimal plannedVolumeUplift, BigDecimal plannedBreakevenUnitVolume, BigDecimal plannedBreakevenUplift, BigDecimal opsoweightingFactor, BigDecimal opsototalGsv, BigDecimal opsototalNsv, BigDecimal opsotradeSpend, BigDecimal opsototalTurnover, BigDecimal opsototalGrossProfit, BigDecimal opsoincrementalGsv, BigDecimal opsoincrementalNsv, BigDecimal opsoincrementalTurnover, BigDecimal opsoincrementalGrossProfit, BigDecimal opsoroi, BigDecimal opsogrossMargin, BigDecimal actualTotalGsv, BigDecimal actualTotalGsvsellIn, BigDecimal actualTotalNsv, BigDecimal actualTradeSpend, BigDecimal actualTotalTurnover, BigDecimal actualTotalCogs, BigDecimal actualTotalGrossProfit, BigDecimal actualIncrementalGsv, BigDecimal actualIncrementalNsv, BigDecimal actualIncrementalTurnover, BigDecimal actualIncrementalGrossProfit, BigDecimal actualRoi, BigDecimal actualGrossMargin, BigDecimal volumeUplift, String exceptionFlag, Long businessRuleId, Integer batchId, Date createdDate, String createdBy) {
    this.promotionFactId = promotionFactId;
    this.promotionId = promotionId;
    this.productId = productId;
    this.customerId = customerId;
    this.baseShipmentUnits = baseShipmentUnits;
    this.baseShipmentCases = baseShipmentCases;
    this.baseUnitVolume = baseUnitVolume;
    this.plannedBaselineDeviationPerc = plannedBaselineDeviationPerc;
    this.totalShippedUnits = totalShippedUnits;
    this.totalShippedCases = totalShippedCases;
    this.totalScannedUnits = totalScannedUnits;
    this.totalUnitVolume = totalUnitVolume;
    this.incrementalUnitVolume = incrementalUnitVolume;
    this.plannedTotalShippedUnits = plannedTotalShippedUnits;
    this.plannedTotalShippedCases = plannedTotalShippedCases;
    this.plannedSellOutUnitVolume = plannedSellOutUnitVolume;
    this.plannedIncrementalUnitVolume = plannedIncrementalUnitVolume;
    this.plannedIncrementalShippedUnits = plannedIncrementalShippedUnits;
    this.plannedIncrementalShippedCases = plannedIncrementalShippedCases;
    this.plannedDipUnits = plannedDipUnits;
    this.adjustmentUnits = adjustmentUnits;
    this.cannibalisedUnits = cannibalisedUnits;
    this.cannibalisedCases = cannibalisedCases;
    this.cannibalisedGsv = cannibalisedGsv;
    this.cannibalisedTurnover = cannibalisedTurnover;
    this.cannibalisedGrossProfit = cannibalisedGrossProfit;
    this.unitsperCase = unitsperCase;
    this.plannedFixedTradeSpend = plannedFixedTradeSpend;
    this.tradeRateperCaseOnInvoice = tradeRateperCaseOnInvoice;
    this.tradeRateperCaseOffInvoice = tradeRateperCaseOffInvoice;
    this.tradeRatePercentofNivonInvoice = tradeRatePercentofNivonInvoice;
    this.tradeRatePercentofNivoffInvoice = tradeRatePercentofNivoffInvoice;
    this.plannedGsvperUnit = plannedGsvperUnit;
    this.plannedNsvperUnit = plannedNsvperUnit;
    this.plannedCogsperUnit = plannedCogsperUnit;
    this.plannedTurnoverperUnit = plannedTurnoverperUnit;
    this.plannedGrossProfitperUnit = plannedGrossProfitperUnit;
    this.baseGsv = baseGsv;
    this.baseNsv = baseNsv;
    this.baseCogs = baseCogs;
    this.baseGrossProfit = baseGrossProfit;
    this.baseGrossMargin = baseGrossMargin;
    this.plannedTotalGsv = plannedTotalGsv;
    this.plannedTotalGsvsellIn = plannedTotalGsvsellIn;
    this.plannedTotalNsv = plannedTotalNsv;
    this.plannedTotalNsvsellIn = plannedTotalNsvsellIn;
    this.plannedTradeSpend = plannedTradeSpend;
    this.plannedTotalTurnover = plannedTotalTurnover;
    this.plannedTotalTurnoverSellIn = plannedTotalTurnoverSellIn;
    this.plannedTotalCogs = plannedTotalCogs;
    this.plannedTotalCogssellIn = plannedTotalCogssellIn;
    this.plannedTotalGrossProfit = plannedTotalGrossProfit;
    this.plannedIncrementalGsv = plannedIncrementalGsv;
    this.plannedIncrementalNsv = plannedIncrementalNsv;
    this.plannedIncrementalTurnover = plannedIncrementalTurnover;
    this.plannedIncrementalGrossProfit = plannedIncrementalGrossProfit;
    this.plannedRoi = plannedRoi;
    this.plannedGrossMargin = plannedGrossMargin;
    this.plannedVolumeUplift = plannedVolumeUplift;
    this.plannedBreakevenUnitVolume = plannedBreakevenUnitVolume;
    this.plannedBreakevenUplift = plannedBreakevenUplift;
    this.opsoweightingFactor = opsoweightingFactor;
    this.opsototalGsv = opsototalGsv;
    this.opsototalNsv = opsototalNsv;
    this.opsotradeSpend = opsotradeSpend;
    this.opsototalTurnover = opsototalTurnover;
    this.opsototalGrossProfit = opsototalGrossProfit;
    this.opsoincrementalGsv = opsoincrementalGsv;
    this.opsoincrementalNsv = opsoincrementalNsv;
    this.opsoincrementalTurnover = opsoincrementalTurnover;
    this.opsoincrementalGrossProfit = opsoincrementalGrossProfit;
    this.opsoroi = opsoroi;
    this.opsogrossMargin = opsogrossMargin;
    this.actualTotalGsv = actualTotalGsv;
    this.actualTotalGsvsellIn = actualTotalGsvsellIn;
    this.actualTotalNsv = actualTotalNsv;
    this.actualTradeSpend = actualTradeSpend;
    this.actualTotalTurnover = actualTotalTurnover;
    this.actualTotalCogs = actualTotalCogs;
    this.actualTotalGrossProfit = actualTotalGrossProfit;
    this.actualIncrementalGsv = actualIncrementalGsv;
    this.actualIncrementalNsv = actualIncrementalNsv;
    this.actualIncrementalTurnover = actualIncrementalTurnover;
    this.actualIncrementalGrossProfit = actualIncrementalGrossProfit;
    this.actualRoi = actualRoi;
    this.actualGrossMargin = actualGrossMargin;
    this.volumeUplift = volumeUplift;
    this.exceptionFlag = exceptionFlag;
    this.businessRuleId = businessRuleId;
    this.batchId = batchId;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
 }

  @Id 

 
 @Column(name="PromotionFactID", unique=true, nullable=false)
 public long getPromotionFactId() {
     return this.promotionFactId;
 }
 
 public void setPromotionFactId(long promotionFactId) {
     this.promotionFactId = promotionFactId;
 }

 
 @Column(name="PromotionID")
 public Long getPromotionId() {
     return this.promotionId;
 }
 
 public void setPromotionId(Long promotionId) {
     this.promotionId = promotionId;
 }

 
 @Column(name="ProductID")
 public Long getProductId() {
     return this.productId;
 }
 
 public void setProductId(Long productId) {
     this.productId = productId;
 }

 
 @Column(name="CustomerID")
 public Long getCustomerId() {
     return this.customerId;
 }
 
 public void setCustomerId(Long customerId) {
     this.customerId = customerId;
 }

 
 @Column(name="BaseShipmentUnits", precision=20, scale=2)
 public BigDecimal getBaseShipmentUnits() {
     return this.baseShipmentUnits;
 }
 
 public void setBaseShipmentUnits(BigDecimal baseShipmentUnits) {
     this.baseShipmentUnits = baseShipmentUnits;
 }

 
 @Column(name="BaseShipmentCases", precision=20, scale=2)
 public BigDecimal getBaseShipmentCases() {
     return this.baseShipmentCases;
 }
 
 public void setBaseShipmentCases(BigDecimal baseShipmentCases) {
     this.baseShipmentCases = baseShipmentCases;
 }

 
 @Column(name="BaseUnitVolume", precision=20, scale=2)
 public BigDecimal getBaseUnitVolume() {
     return this.baseUnitVolume;
 }
 
 public void setBaseUnitVolume(BigDecimal baseUnitVolume) {
     this.baseUnitVolume = baseUnitVolume;
 }

 
 @Column(name="PlannedBaselineDeviationPerc", precision=20, scale=1)
 public BigDecimal getPlannedBaselineDeviationPerc() {
     return this.plannedBaselineDeviationPerc;
 }
 
 public void setPlannedBaselineDeviationPerc(BigDecimal plannedBaselineDeviationPerc) {
     this.plannedBaselineDeviationPerc = plannedBaselineDeviationPerc;
 }

 
 @Column(name="TotalShippedUnits", precision=20, scale=2)
 public BigDecimal getTotalShippedUnits() {
     return this.totalShippedUnits;
 }
 
 public void setTotalShippedUnits(BigDecimal totalShippedUnits) {
     this.totalShippedUnits = totalShippedUnits;
 }

 
 @Column(name="TotalShippedCases", precision=20, scale=2)
 public BigDecimal getTotalShippedCases() {
     return this.totalShippedCases;
 }
 
 public void setTotalShippedCases(BigDecimal totalShippedCases) {
     this.totalShippedCases = totalShippedCases;
 }

 
 @Column(name="TotalScannedUnits", precision=20, scale=0)
 public BigDecimal getTotalScannedUnits() {
     return this.totalScannedUnits;
 }
 
 public void setTotalScannedUnits(BigDecimal totalScannedUnits) {
     this.totalScannedUnits = totalScannedUnits;
 }

 
 @Column(name="TotalUnitVolume", precision=20, scale=0)
 public BigDecimal getTotalUnitVolume() {
     return this.totalUnitVolume;
 }
 
 public void setTotalUnitVolume(BigDecimal totalUnitVolume) {
     this.totalUnitVolume = totalUnitVolume;
 }

 
 @Column(name="IncrementalUnitVolume", precision=20, scale=0)
 public BigDecimal getIncrementalUnitVolume() {
     return this.incrementalUnitVolume;
 }
 
 public void setIncrementalUnitVolume(BigDecimal incrementalUnitVolume) {
     this.incrementalUnitVolume = incrementalUnitVolume;
 }

 
 @Column(name="PlannedTotalShippedUnits", precision=20, scale=0)
 public BigDecimal getPlannedTotalShippedUnits() {
     return this.plannedTotalShippedUnits;
 }
 
 public void setPlannedTotalShippedUnits(BigDecimal plannedTotalShippedUnits) {
     this.plannedTotalShippedUnits = plannedTotalShippedUnits;
 }

 
 @Column(name="PlannedTotalShippedCases", precision=20, scale=0)
 public BigDecimal getPlannedTotalShippedCases() {
     return this.plannedTotalShippedCases;
 }
 
 public void setPlannedTotalShippedCases(BigDecimal plannedTotalShippedCases) {
     this.plannedTotalShippedCases = plannedTotalShippedCases;
 }

 
 @Column(name="PlannedSellOutUnitVolume", precision=20, scale=0)
 public BigDecimal getPlannedSellOutUnitVolume() {
     return this.plannedSellOutUnitVolume;
 }
 
 public void setPlannedSellOutUnitVolume(BigDecimal plannedSellOutUnitVolume) {
     this.plannedSellOutUnitVolume = plannedSellOutUnitVolume;
 }

 
 @Column(name="PlannedIncrementalUnitVolume", precision=20, scale=0)
 public BigDecimal getPlannedIncrementalUnitVolume() {
     return this.plannedIncrementalUnitVolume;
 }
 
 public void setPlannedIncrementalUnitVolume(BigDecimal plannedIncrementalUnitVolume) {
     this.plannedIncrementalUnitVolume = plannedIncrementalUnitVolume;
 }

 
 @Column(name="PlannedIncrementalShippedUnits", precision=20, scale=0)
 public BigDecimal getPlannedIncrementalShippedUnits() {
     return this.plannedIncrementalShippedUnits;
 }
 
 public void setPlannedIncrementalShippedUnits(BigDecimal plannedIncrementalShippedUnits) {
     this.plannedIncrementalShippedUnits = plannedIncrementalShippedUnits;
 }

 
 @Column(name="PlannedIncrementalShippedCases", precision=20, scale=0)
 public BigDecimal getPlannedIncrementalShippedCases() {
     return this.plannedIncrementalShippedCases;
 }
 
 public void setPlannedIncrementalShippedCases(BigDecimal plannedIncrementalShippedCases) {
     this.plannedIncrementalShippedCases = plannedIncrementalShippedCases;
 }

 
 @Column(name="PlannedDipUnits", precision=20, scale=0)
 public BigDecimal getPlannedDipUnits() {
     return this.plannedDipUnits;
 }
 
 public void setPlannedDipUnits(BigDecimal plannedDipUnits) {
     this.plannedDipUnits = plannedDipUnits;
 }

 
 @Column(name="AdjustmentUnits", precision=20, scale=0)
 public BigDecimal getAdjustmentUnits() {
     return this.adjustmentUnits;
 }
 
 public void setAdjustmentUnits(BigDecimal adjustmentUnits) {
     this.adjustmentUnits = adjustmentUnits;
 }

 
 @Column(name="CannibalisedUnits", precision=20, scale=0)
 public BigDecimal getCannibalisedUnits() {
     return this.cannibalisedUnits;
 }
 
 public void setCannibalisedUnits(BigDecimal cannibalisedUnits) {
     this.cannibalisedUnits = cannibalisedUnits;
 }

 
 @Column(name="CannibalisedCases", precision=20, scale=0)
 public BigDecimal getCannibalisedCases() {
     return this.cannibalisedCases;
 }
 
 public void setCannibalisedCases(BigDecimal cannibalisedCases) {
     this.cannibalisedCases = cannibalisedCases;
 }

 
 @Column(name="CannibalisedGSV", precision=20, scale=0)
 public BigDecimal getCannibalisedGsv() {
     return this.cannibalisedGsv;
 }
 
 public void setCannibalisedGsv(BigDecimal cannibalisedGsv) {
     this.cannibalisedGsv = cannibalisedGsv;
 }

 
 @Column(name="CannibalisedTurnover", precision=20, scale=2)
 public BigDecimal getCannibalisedTurnover() {
     return this.cannibalisedTurnover;
 }
 
 public void setCannibalisedTurnover(BigDecimal cannibalisedTurnover) {
     this.cannibalisedTurnover = cannibalisedTurnover;
 }

 
 @Column(name="CannibalisedGrossProfit", precision=20, scale=2)
 public BigDecimal getCannibalisedGrossProfit() {
     return this.cannibalisedGrossProfit;
 }
 
 public void setCannibalisedGrossProfit(BigDecimal cannibalisedGrossProfit) {
     this.cannibalisedGrossProfit = cannibalisedGrossProfit;
 }

 
 @Column(name="UnitsperCase", precision=20, scale=0)
 public BigDecimal getUnitsperCase() {
     return this.unitsperCase;
 }
 
 public void setUnitsperCase(BigDecimal unitsperCase) {
     this.unitsperCase = unitsperCase;
 }

 
 @Column(name="PlannedFixedTradeSpend", precision=20, scale=2)
 public BigDecimal getPlannedFixedTradeSpend() {
     return this.plannedFixedTradeSpend;
 }
 
 public void setPlannedFixedTradeSpend(BigDecimal plannedFixedTradeSpend) {
     this.plannedFixedTradeSpend = plannedFixedTradeSpend;
 }

 
 @Column(name="TradeRateperCaseOnInvoice", precision=20, scale=0)
 public BigDecimal getTradeRateperCaseOnInvoice() {
     return this.tradeRateperCaseOnInvoice;
 }
 
 public void setTradeRateperCaseOnInvoice(BigDecimal tradeRateperCaseOnInvoice) {
     this.tradeRateperCaseOnInvoice = tradeRateperCaseOnInvoice;
 }

 
 @Column(name="TradeRateperCaseOffInvoice", precision=20, scale=0)
 public BigDecimal getTradeRateperCaseOffInvoice() {
     return this.tradeRateperCaseOffInvoice;
 }
 
 public void setTradeRateperCaseOffInvoice(BigDecimal tradeRateperCaseOffInvoice) {
     this.tradeRateperCaseOffInvoice = tradeRateperCaseOffInvoice;
 }

 
 @Column(name="TradeRatePercentofNIVOnInvoice", precision=20, scale=0)
 public BigDecimal getTradeRatePercentofNivonInvoice() {
     return this.tradeRatePercentofNivonInvoice;
 }
 
 public void setTradeRatePercentofNivonInvoice(BigDecimal tradeRatePercentofNivonInvoice) {
     this.tradeRatePercentofNivonInvoice = tradeRatePercentofNivonInvoice;
 }

 
 @Column(name="TradeRatePercentofNIVOffInvoice", precision=20, scale=0)
 public BigDecimal getTradeRatePercentofNivoffInvoice() {
     return this.tradeRatePercentofNivoffInvoice;
 }
 
 public void setTradeRatePercentofNivoffInvoice(BigDecimal tradeRatePercentofNivoffInvoice) {
     this.tradeRatePercentofNivoffInvoice = tradeRatePercentofNivoffInvoice;
 }

 
 @Column(name="PlannedGSVperUnit", precision=20, scale=0)
 public BigDecimal getPlannedGsvperUnit() {
     return this.plannedGsvperUnit;
 }
 
 public void setPlannedGsvperUnit(BigDecimal plannedGsvperUnit) {
     this.plannedGsvperUnit = plannedGsvperUnit;
 }

 
 @Column(name="PlannedNSVperUnit", precision=20, scale=0)
 public BigDecimal getPlannedNsvperUnit() {
     return this.plannedNsvperUnit;
 }
 
 public void setPlannedNsvperUnit(BigDecimal plannedNsvperUnit) {
     this.plannedNsvperUnit = plannedNsvperUnit;
 }

 
 @Column(name="PlannedCOGSperUnit", precision=20, scale=0)
 public BigDecimal getPlannedCogsperUnit() {
     return this.plannedCogsperUnit;
 }
 
 public void setPlannedCogsperUnit(BigDecimal plannedCogsperUnit) {
     this.plannedCogsperUnit = plannedCogsperUnit;
 }

 
 @Column(name="PlannedTurnoverperUnit", precision=20, scale=0)
 public BigDecimal getPlannedTurnoverperUnit() {
     return this.plannedTurnoverperUnit;
 }
 
 public void setPlannedTurnoverperUnit(BigDecimal plannedTurnoverperUnit) {
     this.plannedTurnoverperUnit = plannedTurnoverperUnit;
 }

 
 @Column(name="PlannedGrossProfitperUnit", precision=20, scale=0)
 public BigDecimal getPlannedGrossProfitperUnit() {
     return this.plannedGrossProfitperUnit;
 }
 
 public void setPlannedGrossProfitperUnit(BigDecimal plannedGrossProfitperUnit) {
     this.plannedGrossProfitperUnit = plannedGrossProfitperUnit;
 }

 
 @Column(name="BaseGSV", precision=20, scale=0)
 public BigDecimal getBaseGsv() {
     return this.baseGsv;
 }
 
 public void setBaseGsv(BigDecimal baseGsv) {
     this.baseGsv = baseGsv;
 }

 
 @Column(name="BaseNSV", precision=20, scale=0)
 public BigDecimal getBaseNsv() {
     return this.baseNsv;
 }
 
 public void setBaseNsv(BigDecimal baseNsv) {
     this.baseNsv = baseNsv;
 }

 
 @Column(name="BaseCOGS", precision=20, scale=0)
 public BigDecimal getBaseCogs() {
     return this.baseCogs;
 }
 
 public void setBaseCogs(BigDecimal baseCogs) {
     this.baseCogs = baseCogs;
 }

 
 @Column(name="BaseGrossProfit", precision=20, scale=2)
 public BigDecimal getBaseGrossProfit() {
     return this.baseGrossProfit;
 }
 
 public void setBaseGrossProfit(BigDecimal baseGrossProfit) {
     this.baseGrossProfit = baseGrossProfit;
 }

 
 @Column(name="BaseGrossMargin", precision=20, scale=2)
 public BigDecimal getBaseGrossMargin() {
     return this.baseGrossMargin;
 }
 
 public void setBaseGrossMargin(BigDecimal baseGrossMargin) {
     this.baseGrossMargin = baseGrossMargin;
 }

 
 @Column(name="PlannedTotalGSV", precision=20, scale=0)
 public BigDecimal getPlannedTotalGsv() {
     return this.plannedTotalGsv;
 }
 
 public void setPlannedTotalGsv(BigDecimal plannedTotalGsv) {
     this.plannedTotalGsv = plannedTotalGsv;
 }

 
 @Column(name="PlannedTotalGSVSellIn", precision=20, scale=0)
 public BigDecimal getPlannedTotalGsvsellIn() {
     return this.plannedTotalGsvsellIn;
 }
 
 public void setPlannedTotalGsvsellIn(BigDecimal plannedTotalGsvsellIn) {
     this.plannedTotalGsvsellIn = plannedTotalGsvsellIn;
 }

 
 @Column(name="PlannedTotalNSV", precision=20, scale=0)
 public BigDecimal getPlannedTotalNsv() {
     return this.plannedTotalNsv;
 }
 
 public void setPlannedTotalNsv(BigDecimal plannedTotalNsv) {
     this.plannedTotalNsv = plannedTotalNsv;
 }

 
 @Column(name="PlannedTotalNSVSellIn", precision=20, scale=0)
 public BigDecimal getPlannedTotalNsvsellIn() {
     return this.plannedTotalNsvsellIn;
 }
 
 public void setPlannedTotalNsvsellIn(BigDecimal plannedTotalNsvsellIn) {
     this.plannedTotalNsvsellIn = plannedTotalNsvsellIn;
 }

 
 @Column(name="PlannedTradeSpend", precision=20, scale=2)
 public BigDecimal getPlannedTradeSpend() {
     return this.plannedTradeSpend;
 }
 
 public void setPlannedTradeSpend(BigDecimal plannedTradeSpend) {
     this.plannedTradeSpend = plannedTradeSpend;
 }

 
 @Column(name="PlannedTotalTurnover", precision=20, scale=2)
 public BigDecimal getPlannedTotalTurnover() {
     return this.plannedTotalTurnover;
 }
 
 public void setPlannedTotalTurnover(BigDecimal plannedTotalTurnover) {
     this.plannedTotalTurnover = plannedTotalTurnover;
 }

 
 @Column(name="PlannedTotalTurnoverSellIn", precision=20, scale=2)
 public BigDecimal getPlannedTotalTurnoverSellIn() {
     return this.plannedTotalTurnoverSellIn;
 }
 
 public void setPlannedTotalTurnoverSellIn(BigDecimal plannedTotalTurnoverSellIn) {
     this.plannedTotalTurnoverSellIn = plannedTotalTurnoverSellIn;
 }

 
 @Column(name="PlannedTotalCOGS", precision=20, scale=0)
 public BigDecimal getPlannedTotalCogs() {
     return this.plannedTotalCogs;
 }
 
 public void setPlannedTotalCogs(BigDecimal plannedTotalCogs) {
     this.plannedTotalCogs = plannedTotalCogs;
 }

 
 @Column(name="PlannedTotalCOGSSellIn", precision=20, scale=0)
 public BigDecimal getPlannedTotalCogssellIn() {
     return this.plannedTotalCogssellIn;
 }
 
 public void setPlannedTotalCogssellIn(BigDecimal plannedTotalCogssellIn) {
     this.plannedTotalCogssellIn = plannedTotalCogssellIn;
 }

 
 @Column(name="PlannedTotalGrossProfit", precision=20, scale=2)
 public BigDecimal getPlannedTotalGrossProfit() {
     return this.plannedTotalGrossProfit;
 }
 
 public void setPlannedTotalGrossProfit(BigDecimal plannedTotalGrossProfit) {
     this.plannedTotalGrossProfit = plannedTotalGrossProfit;
 }

 
 @Column(name="PlannedIncrementalGSV", precision=20, scale=0)
 public BigDecimal getPlannedIncrementalGsv() {
     return this.plannedIncrementalGsv;
 }
 
 public void setPlannedIncrementalGsv(BigDecimal plannedIncrementalGsv) {
     this.plannedIncrementalGsv = plannedIncrementalGsv;
 }

 
 @Column(name="PlannedIncrementalNSV", precision=20, scale=0)
 public BigDecimal getPlannedIncrementalNsv() {
     return this.plannedIncrementalNsv;
 }
 
 public void setPlannedIncrementalNsv(BigDecimal plannedIncrementalNsv) {
     this.plannedIncrementalNsv = plannedIncrementalNsv;
 }

 
 @Column(name="PlannedIncrementalTurnover", precision=20, scale=2)
 public BigDecimal getPlannedIncrementalTurnover() {
     return this.plannedIncrementalTurnover;
 }
 
 public void setPlannedIncrementalTurnover(BigDecimal plannedIncrementalTurnover) {
     this.plannedIncrementalTurnover = plannedIncrementalTurnover;
 }

 
 @Column(name="PlannedIncrementalGrossProfit", precision=20, scale=2)
 public BigDecimal getPlannedIncrementalGrossProfit() {
     return this.plannedIncrementalGrossProfit;
 }
 
 public void setPlannedIncrementalGrossProfit(BigDecimal plannedIncrementalGrossProfit) {
     this.plannedIncrementalGrossProfit = plannedIncrementalGrossProfit;
 }

 
 @Column(name="PlannedROI", precision=20, scale=2)
 public BigDecimal getPlannedRoi() {
     return this.plannedRoi;
 }
 
 public void setPlannedRoi(BigDecimal plannedRoi) {
     this.plannedRoi = plannedRoi;
 }

 
 @Column(name="PlannedGrossMargin", precision=20, scale=2)
 public BigDecimal getPlannedGrossMargin() {
     return this.plannedGrossMargin;
 }
 
 public void setPlannedGrossMargin(BigDecimal plannedGrossMargin) {
     this.plannedGrossMargin = plannedGrossMargin;
 }

 
 @Column(name="PlannedVolumeUplift", precision=20, scale=0)
 public BigDecimal getPlannedVolumeUplift() {
     return this.plannedVolumeUplift;
 }
 
 public void setPlannedVolumeUplift(BigDecimal plannedVolumeUplift) {
     this.plannedVolumeUplift = plannedVolumeUplift;
 }

 
 @Column(name="PlannedBreakevenUnitVolume", precision=20, scale=0)
 public BigDecimal getPlannedBreakevenUnitVolume() {
     return this.plannedBreakevenUnitVolume;
 }
 
 public void setPlannedBreakevenUnitVolume(BigDecimal plannedBreakevenUnitVolume) {
     this.plannedBreakevenUnitVolume = plannedBreakevenUnitVolume;
 }

 
 @Column(name="PlannedBreakevenUplift", precision=20, scale=0)
 public BigDecimal getPlannedBreakevenUplift() {
     return this.plannedBreakevenUplift;
 }
 
 public void setPlannedBreakevenUplift(BigDecimal plannedBreakevenUplift) {
     this.plannedBreakevenUplift = plannedBreakevenUplift;
 }

 
 @Column(name="OPSOWeightingFactor", precision=20, scale=0)
 public BigDecimal getOpsoweightingFactor() {
     return this.opsoweightingFactor;
 }
 
 public void setOpsoweightingFactor(BigDecimal opsoweightingFactor) {
     this.opsoweightingFactor = opsoweightingFactor;
 }

 
 @Column(name="OPSOTotalGSV", precision=20, scale=0)
 public BigDecimal getOpsototalGsv() {
     return this.opsototalGsv;
 }
 
 public void setOpsototalGsv(BigDecimal opsototalGsv) {
     this.opsototalGsv = opsototalGsv;
 }

 
 @Column(name="OPSOTotalNSV", precision=20, scale=0)
 public BigDecimal getOpsototalNsv() {
     return this.opsototalNsv;
 }
 
 public void setOpsototalNsv(BigDecimal opsototalNsv) {
     this.opsototalNsv = opsototalNsv;
 }

 
 @Column(name="OPSOTradeSpend", precision=20, scale=0)
 public BigDecimal getOpsotradeSpend() {
     return this.opsotradeSpend;
 }
 
 public void setOpsotradeSpend(BigDecimal opsotradeSpend) {
     this.opsotradeSpend = opsotradeSpend;
 }

 
 @Column(name="OPSOTotalTurnover", precision=20, scale=0)
 public BigDecimal getOpsototalTurnover() {
     return this.opsototalTurnover;
 }
 
 public void setOpsototalTurnover(BigDecimal opsototalTurnover) {
     this.opsototalTurnover = opsototalTurnover;
 }

 
 @Column(name="OPSOTotalGrossProfit", precision=20, scale=0)
 public BigDecimal getOpsototalGrossProfit() {
     return this.opsototalGrossProfit;
 }
 
 public void setOpsototalGrossProfit(BigDecimal opsototalGrossProfit) {
     this.opsototalGrossProfit = opsototalGrossProfit;
 }

 
 @Column(name="OPSOIncrementalGSV", precision=20, scale=0)
 public BigDecimal getOpsoincrementalGsv() {
     return this.opsoincrementalGsv;
 }
 
 public void setOpsoincrementalGsv(BigDecimal opsoincrementalGsv) {
     this.opsoincrementalGsv = opsoincrementalGsv;
 }

 
 @Column(name="OPSOIncrementalNSV", precision=20, scale=0)
 public BigDecimal getOpsoincrementalNsv() {
     return this.opsoincrementalNsv;
 }
 
 public void setOpsoincrementalNsv(BigDecimal opsoincrementalNsv) {
     this.opsoincrementalNsv = opsoincrementalNsv;
 }

 
 @Column(name="OPSOIncrementalTurnover", precision=20, scale=2)
 public BigDecimal getOpsoincrementalTurnover() {
     return this.opsoincrementalTurnover;
 }
 
 public void setOpsoincrementalTurnover(BigDecimal opsoincrementalTurnover) {
     this.opsoincrementalTurnover = opsoincrementalTurnover;
 }

 
 @Column(name="OPSOIncrementalGrossProfit", precision=20, scale=2)
 public BigDecimal getOpsoincrementalGrossProfit() {
     return this.opsoincrementalGrossProfit;
 }
 
 public void setOpsoincrementalGrossProfit(BigDecimal opsoincrementalGrossProfit) {
     this.opsoincrementalGrossProfit = opsoincrementalGrossProfit;
 }

 
 @Column(name="OPSOROI", precision=20, scale=2)
 public BigDecimal getOpsoroi() {
     return this.opsoroi;
 }
 
 public void setOpsoroi(BigDecimal opsoroi) {
     this.opsoroi = opsoroi;
 }

 
 @Column(name="OPSOGrossMargin", precision=20, scale=2)
 public BigDecimal getOpsogrossMargin() {
     return this.opsogrossMargin;
 }
 
 public void setOpsogrossMargin(BigDecimal opsogrossMargin) {
     this.opsogrossMargin = opsogrossMargin;
 }

 
 @Column(name="ActualTotalGSV", precision=20, scale=0)
 public BigDecimal getActualTotalGsv() {
     return this.actualTotalGsv;
 }
 
 public void setActualTotalGsv(BigDecimal actualTotalGsv) {
     this.actualTotalGsv = actualTotalGsv;
 }

 
 @Column(name="ActualTotalGSVSellIn", precision=20, scale=0)
 public BigDecimal getActualTotalGsvsellIn() {
     return this.actualTotalGsvsellIn;
 }
 
 public void setActualTotalGsvsellIn(BigDecimal actualTotalGsvsellIn) {
     this.actualTotalGsvsellIn = actualTotalGsvsellIn;
 }

 
 @Column(name="ActualTotalNSV", precision=20, scale=0)
 public BigDecimal getActualTotalNsv() {
     return this.actualTotalNsv;
 }
 
 public void setActualTotalNsv(BigDecimal actualTotalNsv) {
     this.actualTotalNsv = actualTotalNsv;
 }

 
 @Column(name="ActualTradeSpend", precision=20, scale=2)
 public BigDecimal getActualTradeSpend() {
     return this.actualTradeSpend;
 }
 
 public void setActualTradeSpend(BigDecimal actualTradeSpend) {
     this.actualTradeSpend = actualTradeSpend;
 }

 
 @Column(name="ActualTotalTurnover", precision=20, scale=2)
 public BigDecimal getActualTotalTurnover() {
     return this.actualTotalTurnover;
 }
 
 public void setActualTotalTurnover(BigDecimal actualTotalTurnover) {
     this.actualTotalTurnover = actualTotalTurnover;
 }

 
 @Column(name="ActualTotalCOGS", precision=20, scale=2)
 public BigDecimal getActualTotalCogs() {
     return this.actualTotalCogs;
 }
 
 public void setActualTotalCogs(BigDecimal actualTotalCogs) {
     this.actualTotalCogs = actualTotalCogs;
 }

 
 @Column(name="ActualTotalGrossProfit", precision=20, scale=2)
 public BigDecimal getActualTotalGrossProfit() {
     return this.actualTotalGrossProfit;
 }
 
 public void setActualTotalGrossProfit(BigDecimal actualTotalGrossProfit) {
     this.actualTotalGrossProfit = actualTotalGrossProfit;
 }

 
 @Column(name="ActualIncrementalGSV", precision=20, scale=2)
 public BigDecimal getActualIncrementalGsv() {
     return this.actualIncrementalGsv;
 }
 
 public void setActualIncrementalGsv(BigDecimal actualIncrementalGsv) {
     this.actualIncrementalGsv = actualIncrementalGsv;
 }

 
 @Column(name="ActualIncrementalNSV", precision=20, scale=2)
 public BigDecimal getActualIncrementalNsv() {
     return this.actualIncrementalNsv;
 }
 
 public void setActualIncrementalNsv(BigDecimal actualIncrementalNsv) {
     this.actualIncrementalNsv = actualIncrementalNsv;
 }

 
 @Column(name="ActualIncrementalTurnover", precision=20, scale=2)
 public BigDecimal getActualIncrementalTurnover() {
     return this.actualIncrementalTurnover;
 }
 
 public void setActualIncrementalTurnover(BigDecimal actualIncrementalTurnover) {
     this.actualIncrementalTurnover = actualIncrementalTurnover;
 }

 
 @Column(name="ActualIncrementalGrossProfit", precision=20, scale=2)
 public BigDecimal getActualIncrementalGrossProfit() {
     return this.actualIncrementalGrossProfit;
 }
 
 public void setActualIncrementalGrossProfit(BigDecimal actualIncrementalGrossProfit) {
     this.actualIncrementalGrossProfit = actualIncrementalGrossProfit;
 }

 
 @Column(name="ActualROI", precision=20, scale=2)
 public BigDecimal getActualRoi() {
     return this.actualRoi;
 }
 
 public void setActualRoi(BigDecimal actualRoi) {
     this.actualRoi = actualRoi;
 }

 
 @Column(name="ActualGrossMargin", precision=20, scale=2)
 public BigDecimal getActualGrossMargin() {
     return this.actualGrossMargin;
 }
 
 public void setActualGrossMargin(BigDecimal actualGrossMargin) {
     this.actualGrossMargin = actualGrossMargin;
 }

 
 @Column(name="VolumeUplift", precision=20, scale=0)
 public BigDecimal getVolumeUplift() {
     return this.volumeUplift;
 }
 
 public void setVolumeUplift(BigDecimal volumeUplift) {
     this.volumeUplift = volumeUplift;
 }

 
 @Column(name="ExceptionFlag", length=24)
 public String getExceptionFlag() {
     return this.exceptionFlag;
 }
 
 public void setExceptionFlag(String exceptionFlag) {
     this.exceptionFlag = exceptionFlag;
 }

 
 @Column(name="BusinessRuleID")
 public Long getBusinessRuleId() {
     return this.businessRuleId;
 }
 
 public void setBusinessRuleId(Long businessRuleId) {
     this.businessRuleId = businessRuleId;
 }

 
 @Column(name="BatchID")
 public Integer getBatchId() {
     return this.batchId;
 }
 
 public void setBatchId(Integer batchId) {
     this.batchId = batchId;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="CreatedDate", length=23)
 public Date getCreatedDate() {
     return this.createdDate;
 }
 
 public void setCreatedDate(Date createdDate) {
     this.createdDate = createdDate;
 }

 
 @Column(name="CreatedBy", length=64)
 public String getCreatedBy() {
     return this.createdBy;
 }
 
 public void setCreatedBy(String createdBy) {
     this.createdBy = createdBy;
 }




}


