package com.saama.workbench.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SblProductHierarchy generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_HIERARCHY"
    ,schema="LND"
    
)
public class SblProductHierarchy  implements java.io.Serializable {


     private long productHierarchyID;
     private String ProductName;
     private String ProductCode;
     private String Level1Name;
     private String Level1Code;
     private String Level2Name;
     private String Level2Code;
     private String Level3Name;
     private String Level3Code;
     private String Level4Name;
     private String Level4Code;
     private String Level5Name;
     private String Level5Code;
     private String Level6Name;
     private String Level6Code;
     private String Level7Name;
     private String Level7Code;
     private String Level8Name;
     private String Level8Code;
     private String Level9Name;
     private String Level9Code;
     private String Level10Name;
     private String Level10Code;
     private String Level11Name;
     private String Level11Code;
     private String Level12Name;
     private String Level12Code;
     private String Level13Name;
     private String Level13Code;
     private String IsDeletedFlag;
     private String NaturalKey;
     private String NaturalKeyHash;
     private String RowHash;
     private Integer BatchID;
     private String brandFormCode;
     private Date CreatedDate;
     private String CreatedBy;
     private Date UpdatedDate;
     private String UpdatedBy;
    

    public SblProductHierarchy() {
    }

    @Id     
    @Column(name="ProductHierarchyID", unique=true, nullable=false) 
	public long getProductHierarchyID() {
		return productHierarchyID;
	}


	public void setProductHierarchyID(long productHierarchyID) {
		this.productHierarchyID = productHierarchyID;
	}

	@Column(name="ProductName", length=1024)
	public String getProductName() {
		return ProductName;
	}


	public void setProductName(String productName) {
		ProductName = productName;
	}

	@Column(name="ProductCode", length=1024)
	public String getProductCode() {
		return ProductCode;
	}


	public void setProductCode(String productCode) {
		ProductCode = productCode;
	}

	@Column(name="Level1Name", length=1024)
	public String getLevel1Name() {
		return Level1Name;
	}


	public void setLevel1Name(String level1Name) {
		Level1Name = level1Name;
	}

	@Column(name="Level1Code", length=1024)
	public String getLevel1Code() {
		return Level1Code;
	}


	public void setLevel1Code(String level1Code) {
		Level1Code = level1Code;
	}

	@Column(name="Level2Name", length=1024)
	public String getLevel2Name() {
		return Level2Name;
	}


	public void setLevel2Name(String level2Name) {
		Level2Name = level2Name;
	}

	@Column(name="Level2Code", length=1024)
	public String getLevel2Code() {
		return Level2Code;
	}


	public void setLevel2Code(String level2Code) {
		Level2Code = level2Code;
	}

	@Column(name="Level3Name", length=1024)
	public String getLevel3Name() {
		return Level3Name;
	}


	public void setLevel3Name(String level3Name) {
		Level3Name = level3Name;
	}

	@Column(name="Level3Code", length=1024)
	public String getLevel3Code() {
		return Level3Code;
	}


	public void setLevel3Code(String level3Code) {
		Level3Code = level3Code;
	}

	@Column(name="Level4Name", length=1024)
	public String getLevel4Name() {
		return Level4Name;
	}


	public void setLevel4Name(String level4Name) {
		Level4Name = level4Name;
	}

	@Column(name="Level4Code", length=1024)
	public String getLevel4Code() {
		return Level4Code;
	}


	public void setLevel4Code(String level4Code) {
		Level4Code = level4Code;
	}

	@Column(name="Level5Name", length=1024)
	public String getLevel5Name() {
		return Level5Name;
	}


	public void setLevel5Name(String level5Name) {
		Level5Name = level5Name;
	}

	@Column(name="Level5Code", length=1024)
	public String getLevel5Code() {
		return Level5Code;
	}


	public void setLevel5Code(String level5Code) {
		Level5Code = level5Code;
	}

	@Column(name="Level6Name", length=1024)
	public String getLevel6Name() {
		return Level6Name;
	}


	public void setLevel6Name(String level6Name) {
		Level6Name = level6Name;
	}

	@Column(name="Level6Code", length=1024)
	public String getLevel6Code() {
		return Level6Code;
	}


	public void setLevel6Code(String level6Code) {
		Level6Code = level6Code;
	}

	@Column(name="Level7Name", length=1024)
	public String getLevel7Name() {
		return Level7Name;
	}


	public void setLevel7Name(String level7Name) {
		Level7Name = level7Name;
	}

	@Column(name="Level7Code", length=1024)
	public String getLevel7Code() {
		return Level7Code;
	}


	public void setLevel7Code(String level7Code) {
		Level7Code = level7Code;
	}

	@Column(name="Level8Name", length=1024)
	public String getLevel8Name() {
		return Level8Name;
	}


	public void setLevel8Name(String level8Name) {
		Level8Name = level8Name;
	}

	@Column(name="Level8Code", length=1024)
	public String getLevel8Code() {
		return Level8Code;
	}


	public void setLevel8Code(String level8Code) {
		Level8Code = level8Code;
	}

	@Column(name="Level9Name", length=1024)
	public String getLevel9Name() {
		return Level9Name;
	}


	public void setLevel9Name(String level9Name) {
		Level9Name = level9Name;
	}

	@Column(name="Level9Code", length=1024)
	public String getLevel9Code() {
		return Level9Code;
	}


	public void setLevel9Code(String level9Code) {
		Level9Code = level9Code;
	}

	@Column(name="Level10Name", length=1024)
	public String getLevel10Name() {
		return Level10Name;
	}


	public void setLevel10Name(String level10Name) {
		Level10Name = level10Name;
	}

	@Column(name="Level10Code", length=1024)
	public String getLevel10Code() {
		return Level10Code;
	}


	public void setLevel10Code(String level10Code) {
		Level10Code = level10Code;
	}

	@Column(name="Level11Name", length=1024)
	public String getLevel11Name() {
		return Level11Name;
	}


	public void setLevel11Name(String level11Name) {
		Level11Name = level11Name;
	}

	@Column(name="Level11Code", length=1024)
	public String getLevel11Code() {
		return Level11Code;
	}


	public void setLevel11Code(String level11Code) {
		Level11Code = level11Code;
	}

	@Column(name="Level12Name", length=1024)
	public String getLevel12Name() {
		return Level12Name;
	}


	public void setLevel12Name(String level12Name) {
		Level12Name = level12Name;
	}

	@Column(name="Level12Code", length=1024)
	public String getLevel12Code() {
		return Level12Code;
	}


	public void setLevel12Code(String level12Code) {
		Level12Code = level12Code;
	}

	@Column(name="Level13Name", length=1024)
	public String getLevel13Name() {
		return Level13Name;
	}


	public void setLevel13Name(String level13Name) {
		Level13Name = level13Name;
	}

	@Column(name="Level13Code", length=1024)
	public String getLevel13Code() {
		return Level13Code;
	}


	public void setLevel13Code(String level13Code) {
		Level13Code = level13Code;
	}

	@Column(name="IsDeletedFlag", length=1024)
	public String getIsDeletedFlag() {
		return IsDeletedFlag;
	}


	public void setIsDeletedFlag(String isDeletedFlag) {
		IsDeletedFlag = isDeletedFlag;
	}

	@Column(name="NaturalKey", length=4000)
	public String getNaturalKey() {
		return NaturalKey;
	}


	public void setNaturalKey(String naturalKey) {
		NaturalKey = naturalKey;
	}

	@Column(name="NaturalKeyHash", length=1024)
	public String getNaturalKeyHash() {
		return NaturalKeyHash;
	}


	public void setNaturalKeyHash(String naturalKeyHash) {
		NaturalKeyHash = naturalKeyHash;
	}

	@Column(name="RowHash", length=1024)
	public String getRowHash() {
		return RowHash;
	}


	public void setRowHash(String rowHash) {
		RowHash = rowHash;
	}

	@Column(name="BatchID")
	public Integer getBatchID() {
		return BatchID;
	}


	public void setBatchID(Integer batchID) {
		BatchID = batchID;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CreatedDate")
	public Date getCreatedDate() {
		return CreatedDate;
	}


	public void setCreatedDate(Date createdDate) {
		CreatedDate = createdDate;
	}

	@Column(name="CreatedBy")
	public String getCreatedBy() {
		return CreatedBy;
	}


	public void setCreatedBy(String createdBy) {
		CreatedBy = createdBy;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="UpdatedDate")
	public Date getUpdatedDate() {
		return UpdatedDate;
	}


	public void setUpdatedDate(Date updatedDate) {
		UpdatedDate = updatedDate;
	}

	@Column(name="UpdatedBy", length=1024)
	public String getUpdatedBy() {
		return UpdatedBy;
	}


	public void setUpdatedBy(String updatedBy) {
		UpdatedBy = updatedBy;
	}

	
   
    

}


