package com.saama.workbench.model;
// Generated 8 Jan, 2016 1:57:13 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * StImpl generated by hbm2java
 */
@Entity
@Table(name="st_impl"
    ,schema="harm_app"
   
)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "stImpl")
public class StImpl  implements java.io.Serializable {


     private String implId;
     private String implName;
     private String implClass;
     private String implType;
     private String implCategory;
     private String descr;
     private Byte editable;
     private String lastAuditUser;
     private String lastAuditDisplayName;
     private String lastAuditAuxInfo;
     private Date lastAuditTime;
     private String lastAuditAction;
     private Set<StStep> stSteps = new HashSet<StStep>(0);

    public StImpl() {
    }

	
    public StImpl(String implId, String implName, String implClass, String implType, String implCategory) {
        this.implId = implId;
        this.implName = implName;
        this.implClass = implClass;
        this.implType = implType;
        this.implCategory = implCategory;
    }
    public StImpl(String implId, String implName, String implClass, String implType, String implCategory, String descr, Byte editable, String lastAuditUser, String lastAuditDisplayName, String lastAuditAuxInfo, Date lastAuditTime, String lastAuditAction, Set<StStep> stSteps) {
       this.implId = implId;
       this.implName = implName;
       this.implClass = implClass;
       this.implType = implType;
       this.implCategory = implCategory;
       this.descr = descr;
       this.editable = editable;
       this.lastAuditUser = lastAuditUser;
       this.lastAuditDisplayName = lastAuditDisplayName;
       this.lastAuditAuxInfo = lastAuditAuxInfo;
       this.lastAuditTime = lastAuditTime;
       this.lastAuditAction = lastAuditAction;
       this.stSteps = stSteps;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)      
    @Column(name="impl_id", unique=true, nullable=false)
    public String getImplId() {
        return this.implId;
    }
    
    public void setImplId(String implId) {
        this.implId = implId;
    }

    
    @Column(name="impl_name", nullable=false, length=128)
    public String getImplName() {
        return this.implName;
    }
    
    public void setImplName(String implName) {
        this.implName = implName;
    }

    
    @Column(name="impl_class", nullable=false, length=512)
    public String getImplClass() {
        return this.implClass;
    }
    
    public void setImplClass(String implClass) {
        this.implClass = implClass;
    }

    
    @Column(name="impl_type", nullable=false)
    public String getImplType() {
        return this.implType;
    }
    
    public void setImplType(String implType) {
        this.implType = implType;
    }

    
    @Column(name="impl_category", nullable=false)
    public String getImplCategory() {
        return this.implCategory;
    }
    
    public void setImplCategory(String implCategory) {
        this.implCategory = implCategory;
    }

    
    @Column(name="descr", length=1000)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    
    @Column(name="editable")
    public Byte getEditable() {
        return this.editable;
    }
    
    public void setEditable(Byte editable) {
        this.editable = editable;
    }

    
    @Column(name="last_audit_user")
    public String getLastAuditUser() {
        return this.lastAuditUser;
    }
    
    public void setLastAuditUser(String lastAuditUser) {
        this.lastAuditUser = lastAuditUser;
    }

    
    @Column(name="last_audit_display_name")
    public String getLastAuditDisplayName() {
        return this.lastAuditDisplayName;
    }
    
    public void setLastAuditDisplayName(String lastAuditDisplayName) {
        this.lastAuditDisplayName = lastAuditDisplayName;
    }

    
    @Column(name="last_audit_aux_info", length=512)
    public String getLastAuditAuxInfo() {
        return this.lastAuditAuxInfo;
    }
    
    public void setLastAuditAuxInfo(String lastAuditAuxInfo) {
        this.lastAuditAuxInfo = lastAuditAuxInfo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_audit_time", length=23)
    public Date getLastAuditTime() {
        return this.lastAuditTime;
    }
    
    public void setLastAuditTime(Date lastAuditTime) {
        this.lastAuditTime = lastAuditTime;
    }

    
    @Column(name="last_audit_action", length=1)
    public String getLastAuditAction() {
        return this.lastAuditAction;
    }
    
    public void setLastAuditAction(String lastAuditAction) {
        this.lastAuditAction = lastAuditAction;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stImpl")
    public Set<StStep> getStSteps() {
        return this.stSteps;
    }
    
    public void setStSteps(Set<StStep> stSteps) {
        this.stSteps = stSteps;
    }




}


