package com.saama.workbench.model;
// Generated 8 Jan, 2016 1:57:13 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * StStepParameter generated by hbm2java
 */
@Entity
@Table(name="st_step_parameter"
    ,schema="harm_app"
    
)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "stStepParameter")
public class StStepParameter  implements java.io.Serializable {


     private String stepParamId;
     private StStep stStep;
     private String paramName;
     private String paramVal;
     private String lastAuditUser;
     private String lastAuditDisplayName;
     private String lastAuditAuxInfo;
     private String lastAuditTime;
     private String lastAuditAction;

    public StStepParameter() {
    }

	
    public StStepParameter(String stepParamId, StStep stStep, String paramName, String paramVal) {
        this.stepParamId = stepParamId;
        this.stStep = stStep;
        this.paramName = paramName;
        this.paramVal = paramVal;
    }
    public StStepParameter(String stepParamId, StStep stStep, String paramName, String paramVal, String lastAuditUser, String lastAuditDisplayName, String lastAuditAuxInfo, String lastAuditTime, String lastAuditAction) {
       this.stepParamId = stepParamId;
       this.stStep = stStep;
       this.paramName = paramName;
       this.paramVal = paramVal;
       this.lastAuditUser = lastAuditUser;
       this.lastAuditDisplayName = lastAuditDisplayName;
       this.lastAuditAuxInfo = lastAuditAuxInfo;
       this.lastAuditTime = lastAuditTime;
       this.lastAuditAction = lastAuditAction;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="step_param_id", unique=true, nullable=false)
    public String getStepParamId() {
        return this.stepParamId;
    }
    
    public void setStepParamId(String stepParamId) {
        this.stepParamId = stepParamId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="step_id", nullable=false)
    public StStep getStStep() {
        return this.stStep;
    }
    
    public void setStStep(StStep stStep) {
        this.stStep = stStep;
    }

    
    @Column(name="param_name", nullable=false)
    public String getParamName() {
        return this.paramName;
    }
    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    
    @Column(name="param_val", nullable=false, length=1000)
    public String getParamVal() {
        return this.paramVal;
    }
    
    public void setParamVal(String paramVal) {
        this.paramVal = paramVal;
    }

    
    @Column(name="last_audit_user")
    public String getLastAuditUser() {
        return this.lastAuditUser;
    }
    
    public void setLastAuditUser(String lastAuditUser) {
        this.lastAuditUser = lastAuditUser;
    }

    
    @Column(name="last_audit_display_name")
    public String getLastAuditDisplayName() {
        return this.lastAuditDisplayName;
    }
    
    public void setLastAuditDisplayName(String lastAuditDisplayName) {
        this.lastAuditDisplayName = lastAuditDisplayName;
    }

    
    @Column(name="last_audit_aux_info", length=512)
    public String getLastAuditAuxInfo() {
        return this.lastAuditAuxInfo;
    }
    
    public void setLastAuditAuxInfo(String lastAuditAuxInfo) {
        this.lastAuditAuxInfo = lastAuditAuxInfo;
    }

    
    @Column(name="last_audit_time", length=23)
    public String getLastAuditTime() {
        return this.lastAuditTime;
    }
    
    public void setLastAuditTime(String string) {
        this.lastAuditTime = string;
    }

    
    @Column(name="last_audit_action", length=1)
    public String getLastAuditAction() {
        return this.lastAuditAction;
    }
    
    public void setLastAuditAction(String lastAuditAction) {
        this.lastAuditAction = lastAuditAction;
    }




}


