package com.saama.workbench.model;
// Generated 8 Jan, 2016 1:57:13 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * StStep generated by hbm2java
 */
@Entity
@Table(name="st_step"
    ,schema="harm_app"
    
)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "stStep")
public class StStep  implements java.io.Serializable {


     private String stepId;
     private StImpl stImpl;
     private String stepType;
     private String stepCategory;
     private String stepName;
     private String descr;
     private Byte editable;
     private String lastAuditUser;
     private String lastAuditDisplayName;
     private String lastAuditAuxInfo;
     private Date lastAuditTime;
     private String lastAuditAction;
     private Set<StStepParameter> stStepParameters = new HashSet<StStepParameter>(0);

    public StStep() {
    }

	
    public StStep(String stepId, StImpl stImpl, String stepType, String stepCategory, String stepName) {
        this.stepId = stepId;
        this.stImpl = stImpl;
        this.stepType = stepType;
        this.stepCategory = stepCategory;
        this.stepName = stepName;
    }
    public StStep(String stepId, StImpl stImpl, String stepType, String stepCategory, String stepName, String descr, Byte editable, String lastAuditUser, String lastAuditDisplayName, String lastAuditAuxInfo, Date lastAuditTime, String lastAuditAction, Set<StStepParameter> stStepParameters) {
       this.stepId = stepId;
       this.stImpl = stImpl;
       this.stepType = stepType;
       this.stepCategory = stepCategory;
       this.stepName = stepName;
       this.descr = descr;
       this.editable = editable;
       this.lastAuditUser = lastAuditUser;
       this.lastAuditDisplayName = lastAuditDisplayName;
       this.lastAuditAuxInfo = lastAuditAuxInfo;
       this.lastAuditTime = lastAuditTime;
       this.lastAuditAction = lastAuditAction;
       this.stStepParameters = stStepParameters;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)      
    @Column(name="step_id", unique=true, nullable=false)
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="impl_id", nullable=false)
    public StImpl getStImpl() {
        return this.stImpl;
    }
    
    public void setStImpl(StImpl stImpl) {
        this.stImpl = stImpl;
    }

    
    @Column(name="step_type", nullable=false)
    public String getStepType() {
        return this.stepType;
    }
    
    public void setStepType(String stepType) {
        this.stepType = stepType;
    }

    
    @Column(name="step_category", nullable=false)
    public String getStepCategory() {
        return this.stepCategory;
    }
    
    public void setStepCategory(String stepCategory) {
        this.stepCategory = stepCategory;
    }

    
    @Column(name="step_name", nullable=false, length=128)
    public String getStepName() {
        return this.stepName;
    }
    
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }

    
    @Column(name="descr", length=1000)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    
    @Column(name="editable")
    public Byte getEditable() {
        return this.editable;
    }
    
    public void setEditable(Byte editable) {
        this.editable = editable;
    }

    
    @Column(name="last_audit_user")
    public String getLastAuditUser() {
        return this.lastAuditUser;
    }
    
    public void setLastAuditUser(String lastAuditUser) {
        this.lastAuditUser = lastAuditUser;
    }

    
    @Column(name="last_audit_display_name")
    public String getLastAuditDisplayName() {
        return this.lastAuditDisplayName;
    }
    
    public void setLastAuditDisplayName(String lastAuditDisplayName) {
        this.lastAuditDisplayName = lastAuditDisplayName;
    }

    
    @Column(name="last_audit_aux_info", length=512)
    public String getLastAuditAuxInfo() {
        return this.lastAuditAuxInfo;
    }
    
    public void setLastAuditAuxInfo(String lastAuditAuxInfo) {
        this.lastAuditAuxInfo = lastAuditAuxInfo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_audit_time", length=23)
    public Date getLastAuditTime() {
        return this.lastAuditTime;
    }
    
    public void setLastAuditTime(Date lastAuditTime) {
        this.lastAuditTime = lastAuditTime;
    }

    
    @Column(name="last_audit_action", length=1)
    public String getLastAuditAction() {
        return this.lastAuditAction;
    }
    
    public void setLastAuditAction(String lastAuditAction) {
        this.lastAuditAction = lastAuditAction;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stStep")
    public Set<StStepParameter> getStStepParameters() {
        return this.stStepParameters;
    }
    
    public void setStStepParameters(Set<StStepParameter> stStepParameters) {
        this.stStepParameters = stStepParameters;
    }




}


